apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.env.MYSQL_HOST | quote }}
  MYSQL_PORT: {{ .Values.env.MYSQL_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USERNAME: {{ .Values.env.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
  IAMPORT_KEY: {{ .Values.env.IAMPORT_KEY | quote }}
  IAMPORT_SECRET: {{ .Values.env.IAMPORT_SECRET | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}