apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application-k8s.yml: |
    spring:
      cloud:
        kubernetes:
          discovery:
            namespaces: 
              - popi-user
              - popi-manager

    eureka:
      client:
        enabled: false

    logging:
      level:
        org.hibernate.SQL: debug

    springdoc:
      api-docs:
        version: openapi_3_1
        enabled: true
      enable-kotlin: false
      default-consumes-media-type: application/json
      default-produces-media-type: application/json

    manager:
      service:
        name: manager-service-svc