apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manager-service-ingress
  namespace: popi-manager
  annotations:
    # ALB 기본 설정
    alb.ingress.kubernetes.io/load-balancer-name: {{ LOAD_BALANCER_NAME }}
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing

    # SSL & HTTPS 설정
    alb.ingress.kubernetes.io/certificate-arn: {{ ACM_CERTIFICATE_ARN }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    # Health Check
    alb.ingress.kubernetes.io/healthcheck-path: /manager-actuator/health

    # External DNS
    external-dns.alpha.kubernetes.io/hostname: {{ INGRESS_HOSTNAME }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ INGRESS_HOSTNAME }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manager-service-svc
                port:
                  number: 8080