app:
  name: auth

replicaCount: 1

container:
  image:
    name: 446305434496.dkr.ecr.ap-northeast-2.amazonaws.com/popi-user/popi-auth-service
    tag: 24
    pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

secretKeys:
  - MYSQL_HOST
  - MYSQL_PORT
  - DB_NAME
  - DB_USERNAME
  - DB_PASSWORD
  - REDIS_HOST
  - REDIS_PORT
  - KAKAO_CLIENT_ID
  - KAKAO_CLIENT_SECRET
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET
  - BASE_URL
  - JWT_ACCESS_TOKEN_SECRET
  - JWT_REFRESH_TOKEN_SECRET
  - JWT_ACCESS_TOKEN_EXPIRATION_TIME
  - JWT_REFRESH_TOKEN_EXPIRATION_TIME
  - JWT_ISSUER