apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application-k8s.yml: |
    spring:
      cloud:
        kubernetes:
          discovery:
            namespaces: popi
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
            default_batch_fetch_size: 100
        open-in-view: false
      data:
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}
          password: ${REDIS_PASSWORD:}

    oauth:
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        redirect-uri: ${BASE_URL}/login/oauth2/code/kakao
        grant-type: authorization_code
      google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: ${BASE_URL}/login/oauth2/code/google
        grant-type: authorization_code

    jwt:
      access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
      refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
      access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:3600}
      refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:172800}
      issuer: ${JWT_ISSUER}

    eureka:
      client:
        enabled: false

    logging:
      level:
        org.hibernate.SQL: debug

    spring-doc:
      default-consumes-media-type: application/json
      default-produces-media-type: application/json
      swagger-ui:
        tags-sorter: alpha
        operations-sorter: method
        disable-swagger-default-url: true
        path: /swagger-ui
        doc-expansion: none
