apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  KAKAO_NATIVE_APP_KEY: {{ .Values.env.KAKAO_NATIVE_APP_KEY | quote }}
  GOOGLE_WEB_CLIENT_ID: {{ .Values.env.GOOGLE_WEB_CLIENT_ID | quote }}
  GOOGLE_ANDROID_CLIENT_ID: {{ .Values.env.GOOGLE_ANDROID_CLIENT_ID | quote }}
  GOOGLE_IOS_CLIENT_ID: {{ .Values.env.GOOGLE_IOS_CLIENT_ID | quote }}
  JWT_ACCESS_TOKEN_SECRET: {{ .Values.env.JWT_ACCESS_TOKEN_SECRET | quote }}
  JWT_REFRESH_TOKEN_SECRET: {{ .Values.env.JWT_REFRESH_TOKEN_SECRET | quote }}
  JWT_REGISTER_TOKEN_SECRET: {{ .Values.env.JWT_REGISTER_TOKEN_SECRET | quote }}  
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: {{ .Values.env.JWT_ACCESS_TOKEN_EXPIRATION_TIME | quote }}
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: {{ .Values.env.JWT_REFRESH_TOKEN_EXPIRATION_TIME | quote }}
  JWT_REGISTER_TOKEN_EXPIRATION_TIME: {{ .Values.env.JWT_REGISTER_TOKEN_EXPIRATION_TIME | quote }}
  JWT_ISSUER: {{ .Values.env.JWT_ISSUER | quote }}