apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_HOST: {{ .Values.env.MYSQL_HOST | quote }}
  MYSQL_PORT: {{ .Values.env.MYSQL_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME | quote }}
  DB_USERNAME: {{ .Values.env.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
  REDIS_HOST: {{ .Values.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | quote }}
  KAKAO_NATIVE_APP_KEY: {{ .Values.env.KAKAO_NATIVE_APP_KEY | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | quote }}
  JWT_ACCESS_TOKEN_SECRET: {{ .Values.env.JWT_ACCESS_TOKEN_SECRET | quote }}
  JWT_REFRESH_TOKEN_SECRET: {{ .Values.env.JWT_REFRESH_TOKEN_SECRET | quote }}
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: {{ .Values.env.JWT_ACCESS_TOKEN_EXPIRATION_TIME | quote }}
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: {{ .Values.env.JWT_REFRESH_TOKEN_EXPIRATION_TIME | quote }}
  JWT_ISSUER: {{ .Values.env.JWT_ISSUER | quote }}