app:
  name: popup-service

replicaCount: 1

container:
  image:
    name: 446305434496.dkr.ecr.ap-northeast-2.amazonaws.com/popi-user/popi-popup-service
    tag: 119
    pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
