apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application-k8s.yml: |
    server:
      port: 8000

    spring:
      cloud:
        kubernetes:
          discovery:
            namespaces: popi-user
        gateway:
          routes:
            - id: auth-reissue
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/reissue
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /${segment}
                - RefreshTokenHeaderFilter
            - id: auth-service
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/**
                - Method=GET,POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /${segment}

            - id: member-docs
              uri: lb://member-service-svc
              predicates:
                - Path=/members/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/members/(?<segment>.*), /$\{segment}
            - id: member-service
              uri: lb://member-service-svc
              predicates:
                - Path=/members/**
                - Method=GET,POST,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/members/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter

            - id: reservation-docs
              uri: lb://reservation-service-svc
              predicates:
                - Path=/reservations/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservations/(?<segment>.*), /$\{segment}
            - id: reservation-service
              uri: lb://reservation-service-svc
              predicates:
                - Path=/reservations/**
                - Method=GET,POST,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservations/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter

          globalcors:
            cors-configurations:
              "[/**]":
                allow-credentials: true
                allowed-origins:
                  - http://localhost:3000
                  - https://www.dev.popi.today
                allowed-headers:
                  - "*"
                allowed-methods:
                  - "*"

    eureka:
      client:
        enabled: false

    springdoc:
      enable-kotlin: false
      swagger-ui:
        urls[0]:
          name: 인증 서비스
          url: /auth/v3/api-docs
        urls[1]:
          name: 회원 서비스
          url: /members/v3/api-docs
        urls[2]:
          name: 예약 서비스
          url: /reservations/v3/api-docs

    jwt:
      access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
      issuer: ${JWT_ISSUER}

    logging:
      level:
        org.hibernate.SQL: debug