apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application-k8s.yml: |
    server:
      port: 8000

    spring:
      cloud:
        kubernetes:
          discovery:
            namespaces: popi-user
        gateway:
          routes:
            - id: auth-docs
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - id: auth-social-login
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/social-login
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - id: auth-register
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/register
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
            - id: auth-reissue
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/reissue
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
                - RefreshTokenHeaderFilter
            - id: auth-logout
              uri: lb://auth-service-svc
              predicates:
                - Path=/auth/logout
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/auth/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter

            - id: member-docs
              uri: lb://member-service-svc
              predicates:
                - Path=/members/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/members/(?<segment>.*), /$\{segment}
            - id: member-me
              uri: lb://member-service-svc
              predicates:
                - Path=/members/me
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/members/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter
            - id: member-withdrawal
              uri: lb://member-service-svc
              predicates:
                - Path=/members/withdrawal
                - Method=DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/members/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter

            - id: reservation-docs
              uri: lb://reservation-service-svc
              predicates:
                - Path=/reservations/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservations/(?<segment>.*), /$\{segment}
            - id: reservation-internal
              uri: lb://reservation-service-svc
              predicates:
                - Path=/reservations/internal/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservations/(?<segment>.*), /$\{segment}
            - id: reservation-service
              uri: lb://reservation-service-svc
              predicates:
                - Path=/reservations, /reservations/**
                - Method=GET,POST,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservations(?<segment>/?.*), /$\{segment}
                - JwtAuthenticationFilter

            - id: popup-service
              uri: lb://popup-service-svc
              predicates:
                - Path=/popups, /popups/**
                - Method=GET,POST,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/popups(?<segment>/?.*), /$\{segment}
            
            - id: notification-docs
              uri: lb://notification-service-svc
              predicates:
                - Path=/notifications/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/reservations/(?<segment>.*), /$\{segment}
            - id: notification-service
              uri: lb://notification-service-svc
              predicates:
                - Path=/notifications/**
                - Method=GET,POST,DELETE
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/notifications/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter

            - id: payment-docs
              uri: lb://payment-service-svc
              predicates:
                - Path=/payments/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/payments/(?<segment>.*), /$\{segment}
            - id: payment-service
              uri: lb://payment-service-svc
              predicates:
                - Path=/payments/**
                - Method=POST
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/payments/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter
                  
            - id: item-docs
              uri: lb://item-service-svc
              predicates:
                - Path=/items/v3/api-docs
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/items/(?<segment>.*), /$\{segment}
            - id: item-service
              uri: lb://item-service-svc
              predicates:
                - Path=/items/**
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/items/(?<segment>.*), /$\{segment}
            - id: item-recommendations
              uri: lb://item-service-svc
              predicates:
                - Path=/items/*/recommendations
                - Method=GET
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/items/(?<segment>.*), /$\{segment}
                - JwtAuthenticationFilter

          globalcors:
            cors-configurations:
              "[/**]":
                allow-credentials: true
                allowed-origin-patterns: "[*]"
                allowed-headers:
                  - "*"
                allowed-methods:
                  - "*"

    eureka:
      client:
        enabled: false

    springdoc:
      enable-kotlin: false
      swagger-ui:
        urls[0]:
          name: 인증 서비스
          url: /auth/v3/api-docs
        urls[1]:
          name: 회원 서비스
          url: /members/v3/api-docs
        urls[2]:
          name: 예약 서비스
          url: /reservations/v3/api-docs
        urls[3]:
          name: 팝업 서비스
          url: /popups/v3/api-docs
        urls[4]:
          name: 알림 서비스
          url: /notifications/v3/api-docs
        urls[5]:
          name: 결제 서비스
          url: /payments/v3/api-docs
        urls[6]:
          name: 상품 서비스
          url: /items/v3/api-docs

    jwt:
      access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
      issuer: ${JWT_ISSUER}

    logging:
      level:
        org.hibernate.SQL: debug