apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.name" . }}-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "api-gateway.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "api-gateway.name" . }}
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-gateway.fullname" . }}-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-gateway.fullname" . }}-secret
                  key: JWT_ISSUER
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "api-gateway.fullname" . }}-configmap