apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.container.image.name }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: {{ .Values.app.name }}-config-volume
              mountPath: /config
              readOnly: true

          env:
            - name: TZ
              value: Asia/Seoul
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: JWT_ACCESS_TOKEN_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-secret
                  key: JWT_ISSUER
      volumes:
        - name: {{ .Values.app.name }}-config-volume
          configMap:
            name: {{.Values.app.name}}-configmap
