apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  JWT_ACCESS_TOKEN_SECRET: {{ .Values.env.JWT_ACCESS_TOKEN_SECRET | quote }}
  JWT_ISSUER: {{ .Values.env.JWT_ISSUER | quote }}