apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_ACCESS_TOKEN_SECRET: {{ .Values.env.JWT_ACCESS_TOKEN_SECRET | quote }}
  JWT_ISSUER: {{ .Values.env.JWT_ISSUER | quote }}