apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.name" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "api-gateway.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}