apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: discovery-sa
    namespace: popi-user
  - kind: ServiceAccount
    name: discovery-sa
    namespace: popi-manager
roleRef:
  kind: ClusterRole
  name: kubernetes-discovery-reader
  apiGroup: rbac.authorization.k8s.io