apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterrole
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch