app:
  name: reservation-service

replicaCount: 1

container:
  image:
    name: 446305434496.dkr.ecr.ap-northeast-2.amazonaws.com/popi-user/popi-reservation-service
    tag: 92
    pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

secretKeys:
  - MYSQL_HOST
  - MYSQL_PORT
  - DB_NAME
  - DB_USERNAME
  - DB_PASSWORD
  - REDIS_HOST
  - REDIS_PORT