app:
  name: api-gateway

replicaCount: 1

container:
  image:
    name: 446305434496.dkr.ecr.ap-northeast-2.amazonaws.com/popi-user/popi-api-gateway
    tag: 39
    pullPolicy: Always

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

secretKeys:
  - JWT_ISSUER
  - JWT_ACCESS_TOKEN_SECRET