apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  application-k8s.yml: |
    spring:
      cloud:
        kubernetes:
          discovery:
            namespaces: popi-user
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
            default_batch_fetch_size: 100
        open-in-view: false
            
    eureka:
      client:
        enabled: false

    logging:
      level:
        org.hibernate.SQL: debug

    spring-doc:
      api-docs:
        version: openapi_3_1
        enabled: true
      enable-kotlin: false
      default-consumes-media-type: application/json
      default-produces-media-type: application/json